### ISSUE TITLE
Correction in example documentation - end of line

### ISSUE THREAD

**Issue by mvb-iti** [Tuxdude/logback-colorizer#1]
```javascript
... - %color(%msg%n)</pattern>
```

can result in random empty spaces all over the shop (beginning of the line, mid-text):
![screen shot 2015-06-18 at 16 54 05](https://cloud.githubusercontent.com/assets/1901826/8235583/af8120e6-15da-11e5-92bf-11cab7fc1d0a.png)

```javascript
... - %color(%msg) %n</pattern>
```

fixes the problem:
![screen shot 2015-06-18 at 16 55 09](https://cloud.githubusercontent.com/assets/1901826/8235619/ce930a8a-15da-11e5-82ba-fe7cd80121b3.png)

Gradle 2.4, Java 7, OS X 10.10.3

**Comment by Tuxdude** [comment]
Thanks, updated the README. :+1:  :-)
